# Generated by Django 5.1.2 on 2024-11-16 09:33

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifetime", "0004_lifetime_created_at_lifetime_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifetimeExpectancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("birth_date", models.IntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("life_expectancy", models.FloatField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "birth_date", "sex"),
                        name="unique_document_fields",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("country__isnull", False),
                            ("birth_date__isnull", False),
                            ("sex__isnull", False),
                            _connector="OR",
                        ),
                        name="at_least_one_field_not_null",
                    ),
                ],
            },
        ),
    ]
