# Generated by Django 5.1.2 on 2024-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifetime", "0005_lifetimeexpectancy"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lifetimeexpectancy",
            name="unique_document_fields",
        ),
        migrations.RemoveConstraint(
            model_name="lifetimeexpectancy",
            name="at_least_one_field_not_null",
        ),
        migrations.RenameField(
            model_name="lifetimeexpectancy",
            old_name="birth_date",
            new_name="birth_year",
        ),
        migrations.AddConstraint(
            model_name="lifetimeexpectancy",
            constraint=models.UniqueConstraint(
                fields=("country", "birth_year", "sex"),
                name="unique_document_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="lifetimeexpectancy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country__isnull", False),
                    ("birth_year__isnull", False),
                    ("sex__isnull", False),
                    _connector="OR",
                ),
                name="at_least_one_field_not_null",
            ),
        ),
    ]
