# Generated by Django 5.1.2 on 2024-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lifetime",
            "0006_remove_lifetimeexpectancy_unique_document_fields_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lifetime",
            name="life_expectancy",
            field=models.FloatField(default=90),
        ),
    ]
