# Generated by Django 5.1.2 on 2024-11-02 09:05

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifetime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifetime",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="lifetime",
            name="death_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lifetime",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lifetime",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
